services:
  springboot-twitter:
    container_name: springboot-twitter
    image: goospel/springboot-twitter-linux
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-twitter:3306/twitterdb
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
    networks:
      - twitter-network
    depends_on:
      mysql-twitter:
        condition: service_healthy

  mysql-twitter:
    container_name: mysql-twitter
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: twitterdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3309:3306"
    networks:
      - twitter-network
    healthcheck:
      test: "mysqladmin ping -h localhost -u dev -pdev123 || exit 1"
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  twitter-network:
    driver: bridge
