spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: springboot-twitter
  datasource:
    url: jdbc:mysql://localhost:3309/twitterdb
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.sql: debug
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
