spring:
  application:
    name: springboot-twitter
  datasource:
    url: jdbc:mysql://localhost:3309/twitterdb
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.sql: debug
